# Must be unique in a given SonarQube instance
sonar.projectKey=br.edu.fatec:caramelstray

sonar.projectName=Caramel Stray
sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file.
# Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarcloud.io

# Substitua pela sua organizacao do SonarCloud (geralmente seu usuario do github ou o nome que voce escolheu la)
sonar.organization=elbertjean
sonar.token=${SONAR_TOKEN}